package br.unicamp.ft.ulisses.aula05_drawer2018;

public class Alunos {

    public static Aluno[] alunos = {
            new Aluno("Alex Rafael Da Costa", "101334", R.drawable.alex_rafael, "Sou Alex Rafael da Costa, tenho 26 anos e atualmente resido em Limeira-SP com minha familia. Já morei em São Paulo (onde nasci), Osasco e campinas.<br/><br/> Tentei fazer física licenciatura na UNICAMP de Campinas de 2010 á 2015. Obtive várias experiencias interessantes que levarei pra minha vida toda. Neste curso percebi que não era minha área profissional (apesar de ter experiencias na área ministrando aulas em cursinhos populares e escolas públicas de 20012 á 2015).<br/><br/> Em 2015 consegui fazer uma bolsa trabalho no CEL Unicamp onde obtive contato com a área de TI. Por gostar muito de tecnologia aplicada (experimentação) e jogos digitais logo decidi fazer o curso de TADS aqui em Limeira.<br/><br/><br/> Atualmente participo do projeto TelEduc 5 core, desenvolvido no NIED (Núcleo de Informática Aplicada á Educação). No projeto esta em adamento e visa construir um novo site de ensino a distância.<br/><br/> Em meu lazer costumo ficar com minha família e namorada, jogar RPG on-lines (hoje em dia) ou ler algo de meu interesse (desde assuntos de tecnologia até romances de ficção ou fantasia).",1.75,26,R.drawable.undefined),
            new Aluno("Amadeu Junior De Carvalho", "165484", R.drawable.amadeu_carvalho, "<p>Olá meu nome é Amadeu, vim da cidade de Guarulhos, fiz um curso técnico em informática na Etec Horácio Augusto, Vila Maria-São Paulo, Trabalhei 1 e 6 meses na área de TI desenvolvendo alguns algorítimos simples, foi quando decidi entrar no curso superior.</p> <p>Nas horas livres gosto de tocar violão, estudar idiomas (Francês principalmente), costumo sempre estar na igreja e participo do GOU FT(Grupo de oração universitário), gosto de praticar atividades físicas sempre que posso procuro participar dos treinos das Atléticas.</p>",1.70,25,R.drawable.palmeiras),
            new Aluno("Bruno Eduardo Sumeira", "167992", R.drawable.bruno_sumeira, "<p><span>Olá meu nome é Bruno Eduardo Sumeira, sou de Tambaú-SP, cursei o ensino médio tradicional em minha cidade natal, fiz cursinho em Ribeirão Preto-SP. Em meu tempo livre gosto de praticar esportes -tais como: futebol, musculacão-. </span></p>",1.76,22,R.drawable.saopaulo),
            new Aluno("Bruno Thomé Junior", "168173", R.drawable.bruno_thome, "",1.76,20,R.drawable.palmeiras),
            new Aluno("Caio Felipe Mendes De Sousa", "165425", R.drawable.caio_felipe, "",1.87,21,R.drawable.riobranco_ac),
            new Aluno("Davi Lopes Mezencio", "169759", R.drawable.davi_lopes, "<p>Davi Lopes Mezencio, 20 anos, nascido em Campinas/SP e morador de Paulinia/SP a 19 anos.</p> <p>Cursei o ensino medio na escola EE General Porphyrio da Paz em Paulinia, me formei no ano de 2012, após o ensino medio parei de estudar e fui trabalhar, em 2015 resolvi voltar a estudar e fui cursar Ciencia da Computação na UFG, por estar morando muito longe de casa resolvi voltar e prestar UNICAMP. Meus principais hobbies são ler e jogar. Espero nessa disciplina aprender mais sobre trabalhos cientificos e como fazer os mesmos.</p> <p> </p>",1.85,22,R.drawable.corinthians),
            new Aluno("Dionys Dener Antonio", "119322", R.drawable.dionys_denner, "Tenho 24 anos, atualmente trabalho como Analista de Planejamento na empresa AlertBrasil e espero adquirir conhecimento para poder avançar em minha carreira.", 1.75, 25, R.drawable.corinthians),
            new Aluno("Felipe Tosta Dos Santos", "171225", R.drawable.felipe_tosta, "",1.79,20,R.drawable.pontepreta),
            new Aluno("Felipe Yanagui Gomiero", "171257", R.drawable.felipe_yanagui, "<p>Meu nome é Felipe Yanagui Gomiero, sou de São Paulo e tenho 18 anos de idade.</p> <p>Fiz o ensino médio e técnico de informática na Escola Técnica Estadual de São Paulo, onde foi meu primeiro contato com campo da computação e foi durante esse processo que desenvolvi um interesse pela a área.</p> <p>Fiz um intercâmbio de duração de 2 meses em Toronto, Canadá no ano passado.</p> <p>Neste curso, em uma visão geral, espero que consiga exceder minhas expectativas e que consiga me fornecer as ferramentas certas para que eu possa me tornar um bom profisssional.</p>",1.70,20,R.drawable.undefined),
            new Aluno("Gabriel Henrique Casemiro", "172169", R.drawable.gabriel_casemiro, "<p>Sou nascido e criado em Limeira, estudei o primeiro e o segundo grau no Colégio São José e ingressei na UNICAMP logo após terminar o Ensino Médio.Tenho uma boa experiência em programação no Desenvolvimento Web pois fiz um curso de dois anos que me deu uma boa direção do caminho profissional que queria seguir.Gosto de jogar bola,jogos em geral e também tenho como hobbie programação.Tenho interesse na área de informatica e tudo que ela engloba.Espero desta disciplina que me de uma boa base para que eu possa desenvolver um trabalho cientifico de qualidade, seja para um término de mestrado ou doutorado ou para apenas uma tese.Sobre o curso, tenho certeza pelas poucas aulas que participei que ele me dará uma boa base para que eu possa exercer a profissão de programador muito bem. </span><br/></p>",1.80,20,R.drawable.saopaulo),
            new Aluno("Guilherme Garcia Dos Santos", "173742", R.drawable.gilherme_santos, "<p>  Meu nome é Guilherme Garcia dos Santos, tenho 18 anos e nasci na cidade de Limeira - SP, onde moro atualmente com meus pais.<br/>    Sou técnico em Informática pelo COTIL - UNICAMP, atualmente trabalho na empresa Light System Soft como suporte técnico e como desenvolvedor freelancer para a empresa Chronologika Solutions. Além disso, estou cursando o segundo semestre de Tecnologia em  Analise e Desenvolvimento de Sistemas na Faculdade de Tecnologia da Unicamp.<br/>     Sou apaixonado por novas tecnologias, pelas praticidades que elas nos fornecem e por novos conhecimentos, pois acredito que nada do que aprendemos é em vão, cada aprendizado nos torna pessoas mais interessantes.<br/>      Entre meus valores estão: honestidade, transparência e companheirismo e tenho características como adaptabilidade, facilidade para aprender, coletividade, organização, auto confiança, comunicatividade, responsabilidade e persistência.<br/>      Entre meus interesses profissionais estão: trabalhar em grandes empresas da área de tecnologia e futuramente, talvez, abrir uma empresa própria. Porém, a área acadêmica também me interessa, mesmo que em menor proporção.<br/>      Tenho também alguns hobbies, como: praticar capoeira e outras lutas, tocar violão, cantar e ler livros.<br/>      Por fim, o que espero da disciplina é que me ajude a desenvolver um lado não tão técnico, mas sim uma relação interpessoal, tendo como pontos fortes: trabalho em equipe e a simulação de problemas que possivelmente enfrentarei na vida profissional.</p>",1.75,20,R.drawable.saopaulo),
            new Aluno("Giovanni Gaio Gandolfi", "173341", R.drawable.giovanni_gandolfi, "<p>Atualmente curso Análise de Sistemas (Turma de 2016), nasci em São Paulo, morei la por 2 anos e depois me mudei para Jundiaí, tenho fluência em inglês, já passei por diversas escolas num total de 9 anos de estudo da língua.</p> <p>Não tenho experiência com trabalho, apenas com projetos ou pesquisas.</p> <p>Costumo me focar bastante quando uma tarefa é dada a mim, porém não consigo trocar de tarefa sem que uma tenha sido totalmente finalizada.</p> <p>Como principal hobby eu tenho o futebol, já joguei muito e sou um grande entusiasta.</p>",1.81,20,R.drawable.santos),
            new Aluno("Gustavo Batistic Ribeiro", "174028", R.drawable.gustavo_batistic, "<p>Meu nome é Gustavo Batistic Ribeiro, tenho 18 anos e completo 19 em agosto. Sou nascido e criado em Marília, porém me mudei para Franca ao entrar no colegial.</p> <p>Após o terceiro colegial, entrei em matemática na USP de São Carlos, e lá fiquei por cerca de 3 meses, não precisei de mais que isso para saber que não era o que eu queria para a minha vida. Fiz cursinho no restante do ano e prestei sistemas de informação por ter me apaixonado por programação em São Carlos.</p> <p>Espero que essa disciplina me incentive a fazer pesquisas científicas e a buscar o novo, o que considero muito importante para o meu futuro profissional.</p>",1.90,21,R.drawable.saopaulo),
            new Aluno("João Gabriel Pampanin De Abreu", "175937", R.drawable.joao_gabriel, "<p>Venho de uma cidade do interior de São Paulo chamada Cajobi, que conta com impressionantes 10.000 habitantes, e tenho 18 anos.</p> <p>Estudei tanto o ensino fundamental quanto o médio em escola publica, além de ter feito curso técnico em informática.</p> <p>Nunca fui interessado em esportes, e graças a isso minha pior nota sempre foi em Educação Física.</p> <p>Jogos digitais e leitura são as bases de minha diversão para o tempo livre, além de ter gosto especial por música e seus instrumentos, porém até o momento toco apenas violão.</p> <p>Meus estilos de música favoritos são Rock, MPB e Clássica, porém escuto de todo tipo sem problemas.</p>",1.85,19,R.drawable.corinthians),
            new Aluno("Jose Filipe Calseverini De Toledo", "200039", R.drawable.jose_calseverini, "<p><span>“Nada a declarar no perfil.”</span></p>", 1.78,19,R.drawable.corinthians),
            new Aluno("Kauê Eufrosino Lima", "177650", R.drawable.kaue_eufrosino, "<p>Web Developer specializing in front end development. Experienced manager versed in all stages of the development cycle for dynamic web projects. E-mail: k177650@g.unicamp.br | kaue@cedet.com.br</p>",1.90,21,R.drawable.celtic_fc),
            new Aluno("Kelwin Fálico Mendes", "177691", R.drawable.kelwin_falico, "<p>Sou de Jundiai - SP</p> <p>Minha experiencia profissional é apenas devido ao Técnico em Plásticos no Senai, onde trabalhei na área por cerca de 1 ano e meio, mas sempre gostei da área de tecnologia voltada para mobile principalmente, o que me motivou se matricular nesse curso.</p> <p>Ingressei nesse curso e me mudei para Limeira para aproveitar o máximo e poder trabalhar futuramente com o que gosto realmente que é programação no momento. A logica que adquiro cada vez mais me ajuda em tudo.</p> <p>Sempre gostei de ler, livros de ficção geralmente, livros que viram filmes, assistir series, frequentar festas, além de jogar jogos diversos.</p> <p>Minha expectativa com o curso é me formar um bom profissional.</p>",1.87,21,R.drawable.saopaulo),
            new Aluno("Lais Arcaro Bueno De Campos", "177779", R.drawable.lais_arcaro, "<p>Meu nome é Laís, tenho 18 anos e meu email é lah-bueno@hotmail.com.</p> <p>Fiz ensino médio na Etec Trajano Camargo (2013-2015), onde participei de um projeto social em uma instituição chamada Núcleo de Valorização Humana \"Nova Vida\", a qual atendia crianças carentes.</p> <p>Fiz, também, Técnico em Informática no Cotil (2014-2015), onde tive a oportunidade de fazer curso de Montagem e Manutenção de Computadores no SENAI e curso de Arduino.</p> <p>Em meio ao ano conturbado de 2015, com pressão com vestibular e programas de estágio, as conquistas vieram.</p> <p>Fui estagiária na CI&amp;T no ano de 2016, e trabalho atualmente como Técnica, curso Tecnologia em Análise e Desenvolvimento de Sistemas na UNICAMP, moro em Limeira e tenho inglês intermediário.</p> <p>Apesar de saber que não é fácil trabalhar com tecnologia, por ter muita responsabilidade, onde pessoas podem perder milhões ou, até mesmo, morrer, além de ter muita hora extra por problemas críticos, é essa a área que eu gosto e pretendo seguir.</p>",1.64,20,R.drawable.corinthians),
            new Aluno("Leonardo Martins Medeiros", "159825", R.drawable.leonardo_medeiros, "nada a declarar",1.84,22,R.drawable.pontepreta),
            new Aluno("Lucca Di Bastiani Do Amaral", "182787", R.drawable.lucas_amaral, "<p>Meu nome é Lucca Di Bastiani, sou de São Paulo e tenho 17 anos, porém vou fazer 18 somente ano que vem. Entrei na UNICAMP logo após terminar o ensino médio. Fiz curso técnico em informática integrado com o ensino médio no ITB Brasilio Flores de Azevedo. Sou um pouco tímido e não sou muito fã de esportes, no meu tempo livre gosto muito de assistir séries, ler e jogar.</p> <p>Email: lucca_di@hotmail.com</p>",1.68,19,R.drawable.undefined),
            new Aluno("Mariana De Oliveira Quintiliano", "183711", R.drawable.mariana_quintiliano, "<p>Nada a declarar no perfil.</p>",1.63,19,R.drawable.fla),
            new Aluno("Mateus Hikari Tanaka", "184082", R.drawable.mateus_tanaka, "<p>Nascido no município de Campinas/SP, tenho 19 anos e desde criança sempre me interessei pela área da computação. <br/>Em 2015 concluí meu Técnico de Informática pelo SENAI e dei início em um estágio na área de desenvolvimento de software na empresa CI&amp;T em Campinas, onde estou atuando hoje como CLT.<br/>Para não ficar travado na carreira apenas com o nível técnico optei por cursar o TADS aqui na UNICAMP, curso muito bacana pra mim que estou querendo um diploma de nível superior que abrange a área de desenvolvimento e em questões de tempo de conclusão é menor.</p>", 1.73,21,R.drawable.undefined),
            new Aluno("Maximiliando Nunes Biscaia", "156757", R.drawable.maximiliano_biscaia, "Sou Maximiliano Nunes Biscaia, tenho 21 anos, sou de Cajamar-SP e resido em Limeira desde de 2014. Cursei 2 anos de Engenharia de Telecomunicações na FT e decidi mudar para o curso de Análise de Sistemas devido à maior afinidade com as matérias de programação. No tempo livre costumo acompanhar canais no youtube e ouvir música.",1.67,22,R.drawable.undefined),
            new Aluno("Odair Lopes da Silva Andrade", "175356", R.drawable.odair_andrade, "<p>Nasci e atualmente moro em Araras. Desde pequeno já mexia nos computadores de casa, fazendo uma bagunça tremenda. Começava aí minha curiosidade e interesse sobre a tecnologia.<br/>Acabei indo para uma escola técnica no ensino médio, e fazendo um curso de Informática para Internet, o que me despertou mais a vontade de programar (tive um pouco de aulas de programação neste curso, e acabei gostando). Logo após sair do ensino médio, prestei o vestibular da Unicamp e passei no curso de Análise e Desenvolvimento de Sistemas.</p> <p>Tenho como hobbies sair com os amigos, tocar violão, jogos online.</p>", 1.72, 22, R.drawable.paysandu_pa),
            new Aluno("Renan Eugenio Da Silva", "186468", R.drawable.renan_silva, "<p>Meu nome é Renan Eugênio da Silva, tenho 18 anos de idade, atualmente moro em Campinas - SP. Trabalho em uma concessionaria na parte de Programador de Entrega de Seminovos e curso Analise e Desenvolvimento na Unicamp de Limeira.</p> <p>Por dois anos morei na cidade de Apucarana - PR onde passei na Universidade Estadual do Parana no curso Ciência da Computação e por motivos pessoais no ano de 2015 voltei para Campinas, minha cidade natal.</p> <p>Tenho grande interesse em conseguir um estagio em que possa colocar em pratica o que aprendo na faculdade com possibilidades de efetivação em um futuro não muito distante.</p> <p>Estou bem animado com o curso, principalmente por ser uma nova linguagem de programação e muito solicitada no mercado de trabalho. Creio que abrirá novos caminhos. </p>",1.67,20,R.drawable.undefined),
            new Aluno("Sérgio Ferreira Batista Filho", "187064", R.drawable.sergio_filho, "<p>Atualmente sou estudante de Análise e Desenvolvimento de Sistemas na FT</p> <p>Tenho como hobbies música, estudar idiomas, eletrônica</p> <p> </p> <p>Meu perfil no linkedin: https://www.linkedin.com/in/sergiodeveloper,</p> <p>    e no duolingo: https://www.duolingo.com/sergiodeveloper</p>",1.77,21,R.drawable.undefined),
            new Aluno("Thiago Henrique Viotto", "187583", R.drawable.thiago_viotto, "<p>Sou uma pessoa que gosta muito de refletir. Gosto das coisas certas, e tenho esperança de um mundo melhor (Imagine John Lennon). Curto bastante sistemas, apesar de achar difícil a parte de programação. Tenho personalidades diferentes, nas horas de estudo, procuro sempre o foco, nas horas de trabalho, mantenho a atitude profissional. Mas, também tenho meu lado de humor... Tenho objetivos de aprender muita coisa. Considero o conhecimento, significado de a vida valer a pena. Amo a tecnologia, e espero fazer parte desta evolução um dia. Tenho como hobbies: youtube, música, tecnologia, fifa, futebol.</p> <p>Email: thiagohenriqueviotto1@gmail.com</p>", 1.79, 21, R.drawable.saopaulo),
            new Aluno("Tiago Alves Da Silva", "177697", R.drawable.tiago_silva, "Meu nome é Tiago Alves da Silva, nasci no dia 6 de setembro de 1996, em Limeira.<p>Conclui o ensino fundamental no SESI nº340, o ensino médio e o Curso Técnico em Informatica no COTIL e atualmente estudo na Faculdade de Tecnologia da UNICAMP cursando TADS (Tecnologia em Análise e Desenvolvimento de Sistemas).</p>",1.78,22,R.drawable.undefined),
            new Aluno("Tomás Moreira D Alessandro", "177754", R.drawable.tomas_dalessandro, "",1.77,22,R.drawable.palmeiras),
            new Aluno("Vinícius Deniz Isumi", "206759", R.drawable.vinicius_isumi, "<p>Tenho 18 anos, sou de Campinas e estou cursando TADS, tenho interesse em fazer intercâmbio ou estágio. Até o momento o curso estão cumprindo com minhas expectativas. Curto jogar Overwatch e coisas aleatórias no Steam, se quiser add: Steam: pancakebr / Battle.net: Pancake#11723.</p>",1.75,19,R.drawable.palmeiras),
            new Aluno("Vitor Alexandre Xavier", "188308", R.drawable.vitor_xavier, "<p>Olá amigos. Nasci e cresci em Limeira, tenho 19 anos, gosto de tudo um pouco. Gosto muito de música, e sei tocar alguns instrumentos (não diria que domino nenhum) e recentemente voltei a desenhar. Como todo bom computeiro, também gosto de jogar e de navegar na internet. </p> <p>Trabalhei numa empresa daqui de limeira chamada \"Intesis\", com Java, Java Web e principalmente Android. </p> <p>Tenho muito interesse em design e em como as coisas funcionam, além do processo de criação e em lógica. Espero que este curso amplie meus horizontes e que esta disciplina me dê mais ferramentas e entendimento na área.</p>",1.75,20,R.drawable.santos),
            new Aluno("Weslley Pereira Ramos Lemes", "188655", R.drawable.weslley_lemes, "",1.83,22,R.drawable.saopaulo),
    };
}
